"""NTH DAO plugin contracts and the reviewed built-in plugin host."""

from .audit import PluginAuditError, PluginAuditLog
from .agent_provider import (
    AGENT_SESSION_CAPABILITY_ID,
    AGENT_SESSION_CAPABILITY_VERSION,
    AGENT_SESSION_CONTRACT,
    AGENT_SESSION_INPUT_SCHEMA,
    AGENT_SESSION_MAX_DOCUMENT_BYTES,
    AGENT_SESSION_OUTPUT_SCHEMA,
    agent_session_operation_rule,
    agent_session_protocol_digest,
    agent_session_protocol_document,
    validate_agent_session_input,
    validate_agent_session_identifier,
    validate_agent_session_output,
)

from .contracts import (
    CAPABILITY_CARDINALITIES,
    CAPABILITY_EFFECTS,
    CONSISTENCY_CLASSES,
    FAILURE_SEMANTICS,
    PLUGIN_HOST_API_VERSION,
    PLUGIN_KINDS,
    PLUGIN_MANIFEST_VERSION,
    PLUGIN_PERMISSIONS,
    PERMISSION_RISK_TIER,
    PRIVACY_CLASSES,
    RETENTION_CLASSES,
    SECURITY_CLASSES,
    CapabilityContract,
    CapabilityRequirement,
    PluginContractError,
    PluginManifest,
    ensure_host_api_compatible,
    schema_digest,
    validate_manifest_set,
)
from .host import (
    CapabilityProvider,
    CapabilitySchemas,
    InvocationAuthority,
    PluginAuthorizationError,
    PluginConflictError,
    PluginContext,
    PluginDependencyError,
    PluginFactory,
    PluginHost,
    PluginHostError,
    PluginHostPolicy,
    PluginInvocationContext,
    PluginInvocationError,
    PluginLifecycleError,
    PluginRuntime,
    PluginStatus,
    ProviderBinding,
)
from .schema import PluginSchemaError, validate_instance, validate_schema
from .network import VerifiedPeerEndpoint, normalize_peer_url

__all__ = [
    "AGENT_SESSION_CAPABILITY_ID",
    "AGENT_SESSION_CAPABILITY_VERSION",
    "AGENT_SESSION_CONTRACT",
    "AGENT_SESSION_INPUT_SCHEMA",
    "AGENT_SESSION_MAX_DOCUMENT_BYTES",
    "AGENT_SESSION_OUTPUT_SCHEMA",
    "agent_session_operation_rule",
    "agent_session_protocol_digest",
    "agent_session_protocol_document",
    "validate_agent_session_input",
    "validate_agent_session_identifier",
    "validate_agent_session_output",
    "CAPABILITY_CARDINALITIES",
    "CAPABILITY_EFFECTS",
    "CONSISTENCY_CLASSES",
    "FAILURE_SEMANTICS",
    "PLUGIN_HOST_API_VERSION",
    "PLUGIN_KINDS",
    "PLUGIN_MANIFEST_VERSION",
    "PLUGIN_PERMISSIONS",
    "PERMISSION_RISK_TIER",
    "PRIVACY_CLASSES",
    "RETENTION_CLASSES",
    "SECURITY_CLASSES",
    "CapabilityContract",
    "CapabilityProvider",
    "CapabilityRequirement",
    "CapabilitySchemas",
    "InvocationAuthority",
    "PluginAuthorizationError",
    "PluginAuditError",
    "PluginAuditLog",
    "PluginConflictError",
    "PluginContext",
    "PluginContractError",
    "PluginDependencyError",
    "PluginFactory",
    "PluginHost",
    "PluginHostError",
    "PluginHostPolicy",
    "PluginInvocationContext",
    "PluginInvocationError",
    "PluginLifecycleError",
    "PluginManifest",
    "PluginRuntime",
    "PluginStatus",
    "ProviderBinding",
    "VerifiedPeerEndpoint",
    "PluginSchemaError",
    "ensure_host_api_compatible",
    "schema_digest",
    "normalize_peer_url",
    "validate_instance",
    "validate_manifest_set",
    "validate_schema",
]
