"""Nth DAO commerce state machine.

The market package handles discovery, matching, and claims. Commerce handles
execution, delivery, verification, disputes, and settlement. ``open_trade``
binds a signed market claim to a new trade.

Milestones:
  CS1: signed trade state machine with manual, no-money settlement.
  CS2: commerce-to-market binding and deterministic verification.
  CS3: dispute resolution to settlement, refund, or split settlement.
  CS4: settlement adapters with an injected payment-rail boundary.
"""

from nth_dao.commerce.trade import (
    # States
    STATE_EXECUTING,
    STATE_DELIVERED,
    STATE_VERIFIED,
    STATE_FAILED,
    STATE_SETTLED,
    STATE_DISPUTED,
    STATE_REFUNDED,
    STATE_SPLIT_SETTLED,
    TERMINAL_STATES,
    # Event types, verdicts, and resolutions
    EVENT_TRADE_OPENED,
    EVENT_DELIVERY_SUBMITTED,
    EVENT_VERIFICATION_RECORDED,
    EVENT_SETTLEMENT_RECORDED,
    EVENT_DISPUTE_OPENED,
    EVENT_DISPUTE_RESOLVED,
    VERDICT_PASS,
    VERDICT_FAIL,
    RESOLUTION_SETTLE,
    RESOLUTION_REFUND,
    RESOLUTION_SPLIT,
    # Objects and storage
    TradeEvent,
    TradeStore,
    sign_trade_event,
    verify_trade_event,
    # Transitions
    open_trade,
    submit_delivery,
    record_verification,
    record_settlement,
    open_dispute,
    resolve_dispute,
    # Queries and verification
    trade_state,
    verify_trade,
    # Errors
    TradeRejected,
    TradeConflict,
    # reject reasons
    REJECT_TRADE_NOT_FOUND,
    REJECT_TRADE_EXISTS,
    REJECT_ILLEGAL_TRANSITION,
    REJECT_WRONG_ACTOR,
    REJECT_BAD_VERDICT,
    REJECT_BAD_RESOLUTION,
    REJECT_EVENT_SIG_INVALID,
    REJECT_CHAIN_BROKEN,
)

__all__ = [
    "STATE_EXECUTING",
    "STATE_DELIVERED",
    "STATE_VERIFIED",
    "STATE_FAILED",
    "STATE_SETTLED",
    "STATE_DISPUTED",
    "STATE_REFUNDED",
    "STATE_SPLIT_SETTLED",
    "TERMINAL_STATES",
    "EVENT_TRADE_OPENED",
    "EVENT_DELIVERY_SUBMITTED",
    "EVENT_VERIFICATION_RECORDED",
    "EVENT_SETTLEMENT_RECORDED",
    "EVENT_DISPUTE_OPENED",
    "EVENT_DISPUTE_RESOLVED",
    "VERDICT_PASS",
    "VERDICT_FAIL",
    "RESOLUTION_SETTLE",
    "RESOLUTION_REFUND",
    "RESOLUTION_SPLIT",
    "TradeEvent",
    "TradeStore",
    "sign_trade_event",
    "verify_trade_event",
    "open_trade",
    "submit_delivery",
    "record_verification",
    "record_settlement",
    "open_dispute",
    "resolve_dispute",
    "trade_state",
    "verify_trade",
    "TradeRejected",
    "TradeConflict",
    "REJECT_TRADE_NOT_FOUND",
    "REJECT_TRADE_EXISTS",
    "REJECT_ILLEGAL_TRANSITION",
    "REJECT_WRONG_ACTOR",
    "REJECT_BAD_VERDICT",
    "REJECT_BAD_RESOLUTION",
    "REJECT_EVENT_SIG_INVALID",
    "REJECT_CHAIN_BROKEN",
    # CS2a binding
    "verify_trade_binding",
    # CS2b verifier
    "DeterministicTestVerifier",
    "VerificationOutcome",
    "sign_test_execution_receipt",
    "SKU_TEST_EXECUTION",
    # CS4 settlement adapters
    "SettlementIntent",
    "SettlementResult",
    "SettlementAdapter",
    "ManualSettlementAdapter",
    "X402SettlementAdapter",
    "PaymentRail",
    "RailReceipt",
    "FakePaymentRail",
    "SettlementFailed",
    "settlement_idempotency_key",
    "settlement_payload",
    "settle_trade",
    "verify_settlement",
    "ADAPTER_MANUAL",
    "ADAPTER_X402_TESTNET",
    "KNOWN_ADAPTERS",
    "SUPPORTED_CURRENCIES",
    "REJECT_UNKNOWN_ADAPTER",
    "REJECT_AMOUNT_INVALID",
    "REJECT_AMOUNT_MISMATCH",
    "REJECT_CURRENCY_UNSUPPORTED",
    "REJECT_CURRENCY_MISMATCH",
    "REJECT_PAYEE_MISMATCH",
    "REJECT_PAYER_MISMATCH",
    "REJECT_TX_REF_MISSING",
    "REJECT_NETWORK_MISSING",
    "REJECT_NETWORK_NOT_TESTNET",
    "REJECT_PROOF_MISSING",
    "REJECT_RECEIPT_INVALID",
    "REJECT_RECEIPT_NOT_CONFIRMED",
    "REJECT_RECEIPT_TOO_LARGE",
    "REJECT_RECEIPT_NOT_FOUND",
    "REJECT_IDEMPOTENCY_KEY_MISMATCH",
    "REJECT_INTENT_INVALID",
    "REJECT_SCHEMA_INVALID",
    "REJECT_SETTLED_AT_INVALID",
    "X402_TEST_NETWORKS",
    "RAIL_RECEIPT_CONFIRMED",
]

from nth_dao.commerce.binding import (
    verify_trade_binding,
    REJECT_NO_OPENED,
    REJECT_ANN_ID_MISMATCH,
    REJECT_ANN_SIG_INVALID,
    REJECT_PUBLISHER_MISMATCH,
    REJECT_CLAIM_RECEIPT_INVALID,
    REJECT_CLAIMANT_MISMATCH,
    REJECT_CLAIM_ANN_MISMATCH,
    REJECT_CLAIM_RECEIPT_ID_MISMATCH,
)
from nth_dao.commerce.verifier import (
    DeterministicTestVerifier,
    VerificationOutcome,
    sign_test_execution_receipt,
    SKU_TEST_EXECUTION,
)
from nth_dao.commerce.settlement import (
    SettlementIntent,
    SettlementResult,
    SettlementAdapter,
    ManualSettlementAdapter,
    X402SettlementAdapter,
    PaymentRail,
    RailReceipt,
    FakePaymentRail,
    SettlementFailed,
    settlement_idempotency_key,
    settlement_payload,
    settle_trade,
    verify_settlement,
    ADAPTER_MANUAL,
    ADAPTER_X402_TESTNET,
    KNOWN_ADAPTERS,
    SUPPORTED_CURRENCIES,
    REJECT_UNKNOWN_ADAPTER,
    REJECT_AMOUNT_INVALID,
    REJECT_AMOUNT_MISMATCH,
    REJECT_CURRENCY_UNSUPPORTED,
    REJECT_CURRENCY_MISMATCH,
    REJECT_PAYEE_MISMATCH,
    REJECT_PAYER_MISMATCH,
    REJECT_TX_REF_MISSING,
    REJECT_NETWORK_MISSING,
    REJECT_NETWORK_NOT_TESTNET,
    REJECT_PROOF_MISSING,
    REJECT_RECEIPT_INVALID,
    REJECT_RECEIPT_NOT_CONFIRMED,
    REJECT_RECEIPT_TOO_LARGE,
    REJECT_RECEIPT_NOT_FOUND,
    REJECT_IDEMPOTENCY_KEY_MISMATCH,
    REJECT_INTENT_INVALID,
    REJECT_SCHEMA_INVALID,
    REJECT_SETTLED_AT_INVALID,
    X402_TEST_NETWORKS,
    RAIL_RECEIPT_CONFIRMED,
)

# Signed commerce catalog and authorised ordering.
from nth_dao.commerce.money import (
    ASSET_DECIMALS,
    MoneyRejected,
    decimal_to_minor,
    minor_to_decimal,
)
from nth_dao.commerce.listing import (
    LISTING_PRODUCT,
    LISTING_SERVICE,
    LISTING_TYPES,
    ListingRejected,
    ListingStore,
    SignedListing,
    listing_digest,
    sign_listing,
    verify_listing,
)
from nth_dao.commerce.listing_announcement import (
    listing_offer_uri,
    publish_listing_announcement,
    verify_listing_announcement_binding,
)
from nth_dao.commerce.order import (
    EVENT_ORDER_CREATED,
    STATE_CREATED,
    OrderConflict,
    OrderEvent,
    OrderRejected,
    OrderStore,
    create_order,
    order_id_for_payment,
    verify_order,
    verify_order_event,
)
from nth_dao.commerce.checkout import CheckoutRejected, create_order_from_mandates
from nth_dao.commerce.order_trade import (
    OrderTradeRejected,
    open_commerce_trade,
    verify_order_trade_binding,
)
from nth_dao.commerce.outbox import (
    CommerceAck,
    CommerceEnvelope,
    CommerceEnvelopeRejected,
    CommerceInbox,
    CommerceOutbox,
    InboxRecord,
    OutboxRecord,
    sign_ack,
    sign_envelope,
    trade_chain_head,
    verify_ack,
    verify_envelope,
)
from nth_dao.commerce.projection import (
    CommerceProjectionRejected,
    list_order_views,
    project_order,
)
from nth_dao.commerce.reconciliation import CommerceReconciler, ReconcilerConfig
from nth_dao.commerce.provisional import (
    ProvisionalImport as ProvisionalImport,
    ProvisionalImportRejected as ProvisionalImportRejected,
    ProvisionalImportStore as ProvisionalImportStore,
)
from nth_dao.commerce.payment_attempt import (
    PaymentAttemptConflict,
    PaymentAttemptExecutor,
    PaymentAttemptReconciler,
    PaymentAttemptEvent,
    PaymentAttemptRejected,
    PaymentAttemptStore,
    PaymentAttemptView,
    PaymentExecutorConfig,
    verify_payment_attempt,
)
from nth_dao.commerce.payment_witness import (
    FilePaymentAttemptHeadWitness,
    PaymentAttemptHeadWitness,
    PaymentWitnessRejected,
)

__all__ += [
    "verify_trade_binding", "REJECT_NO_OPENED", "REJECT_ANN_ID_MISMATCH",
    "REJECT_ANN_SIG_INVALID", "REJECT_PUBLISHER_MISMATCH",
    "REJECT_CLAIM_RECEIPT_INVALID", "REJECT_CLAIMANT_MISMATCH",
    "REJECT_CLAIM_ANN_MISMATCH", "REJECT_CLAIM_RECEIPT_ID_MISMATCH",
    "ASSET_DECIMALS", "MoneyRejected", "decimal_to_minor", "minor_to_decimal",
    "LISTING_PRODUCT", "LISTING_SERVICE", "LISTING_TYPES", "ListingRejected",
    "ListingStore", "SignedListing", "listing_digest", "sign_listing",
    "verify_listing", "listing_offer_uri", "publish_listing_announcement",
    "verify_listing_announcement_binding",
    "EVENT_ORDER_CREATED", "STATE_CREATED", "OrderConflict",
    "OrderEvent", "OrderRejected", "OrderStore", "create_order",
    "order_id_for_payment", "verify_order", "verify_order_event",
    "CheckoutRejected", "create_order_from_mandates",
    "OrderTradeRejected", "open_commerce_trade", "verify_order_trade_binding",
    "CommerceAck", "CommerceEnvelope", "CommerceEnvelopeRejected",
    "CommerceInbox", "CommerceOutbox", "InboxRecord", "OutboxRecord",
    "sign_ack", "sign_envelope", "trade_chain_head", "verify_ack",
    "verify_envelope",
    "CommerceProjectionRejected", "list_order_views", "project_order",
    "CommerceReconciler", "ReconcilerConfig",
    "PaymentAttemptConflict", "PaymentAttemptExecutor", "PaymentAttemptEvent",
    "PaymentAttemptReconciler",
    "PaymentAttemptRejected", "PaymentAttemptStore", "PaymentAttemptView",
    "PaymentExecutorConfig", "verify_payment_attempt",
    "FilePaymentAttemptHeadWitness", "PaymentAttemptHeadWitness",
    "PaymentWitnessRejected",
]
