"""Local-first active task and trade-offer market primitives.

The core flow is Announce -> Feed -> Match -> Claim. This package complements
``nth_dao.marketplace`` rather than replacing its claim, submission, acceptance,
and credit state machines.

The public surface covers durable feeds, subscription matching, atomic claims,
signed receipts, federated digest discovery, mission progress, explainable
reputation, and declarative Resource Profile Skills.
"""

from nth_dao.market.announcement import (
    TaskAnnouncement,
    NTH_ANNOUNCEMENT_KIND_V1,
    NTH_ANNOUNCEMENT_KIND_V2,
    NTH_ANNOUNCEMENT_KIND_V3,
    NTH_TRADE_OFFER_ANNOUNCEMENT_KIND_V1,
    announcement_listing_type,
    sign_announcement,
    verify_announcement,
    announcement_federation_key,
    REJECT_ANN_MISSING_FIELD,
    REJECT_ANN_BAD_PUBLISHER_DID,
    REJECT_ANN_SIG_INVALID,
    REJECT_ANN_SIG_DECODE_FAILED,
    REJECT_ANN_CRYPTO_UNAVAILABLE,
    REJECT_ANN_SCHEMA_INVALID,
)
from nth_dao.market.feed import MarketFeed, PollResult
from nth_dao.market.trade_offer_announcement import (
    MAX_TRADE_OFFER_HEAD_PROOF_BYTES,
    MAX_TRADE_OFFER_HEAD_PROOF_CLOCK_SKEW_MS,
    MAX_TRADE_OFFER_HEAD_PROOF_REVISIONS,
    MAX_TRADE_OFFER_ANNOUNCEMENT_TTL_MS,
    TRADE_OFFER_HEAD_PROOF_KIND_V1,
    VerifiedTradeOfferHeadProof,
    build_trade_offer_head_proof,
    create_trade_offer_announcement,
    trade_offer_head_proof_uri,
    trade_offer_uri,
    verify_trade_offer_announcement_binding,
)
from nth_dao.market.subscription import MarketSubscription
from nth_dao.market.match import (
    match,
    poll_matching,
    MatchResult,
    ScoredAnnouncement,
    MatchingPollResult,
    REJECT_EXPIRED,
    REJECT_CAP_INSUFFICIENT,
    REJECT_CONTEXT_NOT_SUBSCRIBED,
    REJECT_REWARD_BELOW_FLOOR,
    REJECT_PUBLISHER_BELOW_TRUST,
)
from nth_dao.market import vocabulary
from nth_dao.market.federation import (
    FeedDigest,
    build_digest,
    verify_digest,
    match_digest_refs,
    merge_digest_refs,
    pull_announcements,
    pull_announcements_by_keys,
    REJECT_DIGEST_MISSING_FIELD,
    REJECT_DIGEST_BAD_SOURCE_DID,
    REJECT_DIGEST_SIG_INVALID,
    REJECT_DIGEST_SIG_DECODE_FAILED,
    REJECT_DIGEST_CRYPTO_UNAVAILABLE,
    REJECT_DIGEST_SCHEMA_INVALID,
)
from nth_dao.market.claim import (
    claim_announcement,
    sign_claim_receipt,
    record_foreign_claim,
    verify_claim_record,
    ClaimStore,
    ClaimOutcome,
    ClaimConflict,
    ClaimRejected,
    REJECT_ANN_NOT_FOUND,
    REJECT_ANN_EXPIRED,
    REJECT_CAP_TOKEN_INVALID,
    REJECT_SUBJECT_MISMATCH,
    REJECT_SKILL_INSUFFICIENT,
    REJECT_CLAIMANT_BELOW_POLICY,
    REJECT_CLAIMANT_REP_MISSING,
    REJECT_RECEIPT_INVALID,
    REJECT_RECEIPT_BINDING,
    CLAIM_STATUS_CLAIMED,
)
from nth_dao.market.reputation import (
    ReputationProfile,
    compute_reputation,
)
from nth_dao.market.mission_link import (
    MissionProgress,
    MissionClaim,
    mission_progress,
)
from nth_dao.market.claim_ack import (
    AUTHORITY_CLAIM_ACK_KIND,
    AuthorityClaimAckStore,
    sign_authority_claim_ack,
    verify_authority_claim_ack,
)
from nth_dao.market.resource_profile import (
    PROFILE_KIND,
    PROFILE_PROTOCOL_VERSION,
    ResourceProfile,
    ResourceProfilePolicy,
    ResourceProfileRejected,
    ResourceProfileStore,
    evaluate_resource_profile,
    map_community_category,
    resource_profile_body,
    sign_resource_profile,
    validate_profile_attributes,
    verify_resource_profile,
)
from nth_dao.market.resource_profile_id import (
    RESOURCE_PROFILE_ID_MAX_LENGTH,
    validate_resource_profile_id,
)

__all__ = [
    # M1
    "TaskAnnouncement",
    "NTH_ANNOUNCEMENT_KIND_V1",
    "NTH_ANNOUNCEMENT_KIND_V2",
    "NTH_ANNOUNCEMENT_KIND_V3",
    "NTH_TRADE_OFFER_ANNOUNCEMENT_KIND_V1",
    "announcement_listing_type",
    "sign_announcement",
    "verify_announcement",
    "announcement_federation_key",
    "MarketFeed",
    "PollResult",
    "MAX_TRADE_OFFER_ANNOUNCEMENT_TTL_MS",
    "MAX_TRADE_OFFER_HEAD_PROOF_BYTES",
    "MAX_TRADE_OFFER_HEAD_PROOF_CLOCK_SKEW_MS",
    "MAX_TRADE_OFFER_HEAD_PROOF_REVISIONS",
    "TRADE_OFFER_HEAD_PROOF_KIND_V1",
    "VerifiedTradeOfferHeadProof",
    "build_trade_offer_head_proof",
    "create_trade_offer_announcement",
    "trade_offer_head_proof_uri",
    "trade_offer_uri",
    "verify_trade_offer_announcement_binding",
    "REJECT_ANN_MISSING_FIELD",
    "REJECT_ANN_BAD_PUBLISHER_DID",
    "REJECT_ANN_SIG_INVALID",
    "REJECT_ANN_SIG_DECODE_FAILED",
    "REJECT_ANN_CRYPTO_UNAVAILABLE",
    "REJECT_ANN_SCHEMA_INVALID",
    # M2
    "MarketSubscription",
    "match",
    "poll_matching",
    "MatchResult",
    "ScoredAnnouncement",
    "MatchingPollResult",
    "vocabulary",
    "REJECT_EXPIRED",
    "REJECT_CAP_INSUFFICIENT",
    "REJECT_CONTEXT_NOT_SUBSCRIBED",
    "REJECT_REWARD_BELOW_FLOOR",
    "REJECT_PUBLISHER_BELOW_TRUST",
    # M3
    "claim_announcement",
    "sign_claim_receipt",
    "record_foreign_claim",
    "verify_claim_record",
    "ClaimStore",
    "ClaimOutcome",
    "ClaimConflict",
    "ClaimRejected",
    "REJECT_ANN_NOT_FOUND",
    "REJECT_ANN_EXPIRED",
    "REJECT_CAP_TOKEN_INVALID",
    "REJECT_SUBJECT_MISMATCH",
    "REJECT_SKILL_INSUFFICIENT",
    "REJECT_RECEIPT_INVALID",
    "REJECT_RECEIPT_BINDING",
    "CLAIM_STATUS_CLAIMED",
    # M4 federation
    "FeedDigest",
    "build_digest",
    "verify_digest",
    "match_digest_refs",
    "merge_digest_refs",
    "pull_announcements",
    "pull_announcements_by_keys",
    "REJECT_DIGEST_MISSING_FIELD",
    "REJECT_DIGEST_BAD_SOURCE_DID",
    "REJECT_DIGEST_SIG_INVALID",
    "REJECT_DIGEST_SIG_DECODE_FAILED",
    "REJECT_DIGEST_CRYPTO_UNAVAILABLE",
    "REJECT_DIGEST_SCHEMA_INVALID",
    # M5 reputation + mission link + claimant gating
    "ReputationProfile",
    "compute_reputation",
    "MissionProgress",
    "MissionClaim",
    "mission_progress",
    "REJECT_CLAIMANT_BELOW_POLICY",
    "REJECT_CLAIMANT_REP_MISSING",
    "AUTHORITY_CLAIM_ACK_KIND",
    "AuthorityClaimAckStore",
    "sign_authority_claim_ack",
    "verify_authority_claim_ack",
    # Resource Profile Skills
    "PROFILE_KIND",
    "PROFILE_PROTOCOL_VERSION",
    "RESOURCE_PROFILE_ID_MAX_LENGTH",
    "ResourceProfile",
    "ResourceProfilePolicy",
    "ResourceProfileRejected",
    "ResourceProfileStore",
    "evaluate_resource_profile",
    "map_community_category",
    "resource_profile_body",
    "sign_resource_profile",
    "validate_profile_attributes",
    "validate_resource_profile_id",
    "verify_resource_profile",
]
