"""Safe workspace allocation for executable examples."""

from __future__ import annotations

import re
import tempfile
import uuid
from pathlib import Path


_SAFE_NAME = re.compile(r"^[a-z0-9][a-z0-9-]{0,47}$")
_MARKER = ".nth-dao-demo-workspace"


def new_demo_workspace(name: str) -> Path:
    """Return a unique, not-yet-created path under the OS temp directory."""
    if not isinstance(name, str) or not _SAFE_NAME.fullmatch(name):
        raise ValueError("demo workspace name must be a bounded lowercase slug")
    return (
        Path(tempfile.gettempdir()).resolve()
        / f"nth-dao-{name}-{uuid.uuid4().hex}"
    )


def prepare_demo_workspace(path: Path) -> Path:
    """Create a fresh demo workspace without removing any existing path."""
    resolved = path.resolve()
    temp_root = Path(tempfile.gettempdir()).resolve()
    if resolved.parent != temp_root or not resolved.name.startswith("nth-dao-"):
        raise ValueError("demo workspace must be a direct child of the OS temp directory")
    resolved.mkdir(parents=False, exist_ok=False)
    (resolved / _MARKER).write_text(
        "Generated by an NTH DAO example. No user workspace was modified.\n",
        encoding="ascii",
    )
    return resolved
